apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.cd-visibility-trigger.cd-visibility-webhook: ""
  name: ${{ values.destination.owner }}-${{ values.name }}
spec:
  destination:
    namespace: app-${{ values.destination.owner }}-${{ values.name }}
    server: https://kubernetes.default.svc
  source:
    path: deploy/kustomize/overlays/kind
    repoURL: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}.git
    targetRevision: main
  project: kind-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
