apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-go-api-template
  description: An example of a Backstage template.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: group:guests
  lifecycle: experimental
