apiVersion: v1
kind: Service
metadata:
  name: hello-world-api-go
  namespace: hello-world-api-go
spec:
  selector:
    app: hello-world-api-go
  ports:
    - name: http
      port: 80
      targetPort: http