apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-kind.yaml

# Kind-friendly defaults
images:
  - name: ghcr.io/${{ values.destination.owner }}/${{ values.destination.repo }}
    newTag: latest
